M48
; DRILL file {KiCad 8.0.7-5-g6f92c4cccf} date 2025-01-08T11:04:39+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-08T11:04:39+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-5-g6f92c4cccf
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X2.131Y-7.26
X2.131Y-13.04
T2
X-0.36Y-2.19
X-0.36Y-18.11
X25.84Y-2.19
X25.84Y-18.11
M30
